version: '3'

services:
  # Сервис для бэкенда Django
  backend:
    build:
      context: ./deploy/python  # Указываем директорию с Dockerfile для бэкенда
      dockerfile: Dockerfile    # Указываем путь к Dockerfile для бэкенда
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./media:/app/media  # Для хранения медиафайлов
      - ./static:/app/static  # Для хранения статики
    environment:
      - DEBUG=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=budget_tracker
      - DB_USER=postgres
      - DB_PASSWORD=kbpf
    depends_on:
      - db
    restart: always

  # Сервис для фронтенда Vue.js
  frontend:
    build:
      context: ./deploy/frontend  # Указываем путь к проекту Vue.js
      dockerfile: Dockerfile      # Указываем путь к Dockerfile для фронтенда
    container_name: vue-frontend
    ports:
      - "8080:80"  # Проброс порта для фронтенда (обычно 80 для Nginx)
    volumes:
      - ./frontend:/app
    restart: always

  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:14
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kbpf
      POSTGRES_DB: budget_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: